#%RAML 1.0 DataType
type: object
properties:
  CustomerName:
    properties:
      FirstName?: string
      MiddleName?: string
      LastNsame?: string
  age?: string
  sex?: string
  Adress:
    properties:
      AddressLine1?: string
      AddressLine2?: 
       enum: [CEDS, MP, EMS]
       

 
     


